---

services:
  varnish:
    image: varnish:7.6.1
    # image: varnish:7.6.1-alpine
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
      - ./varnish/docker-varnish-entrypoint.sh:/usr/local/bin/docker-varnish-entrypoint:ro
      - ./varnish/ncsa-log:/var/log/varnish/
    environment:
      VARNISH_SIZE: 2G
      TZ: Asia/Tokyo
    depends_on:
      - nginx
    ports:
      - "80:80"
    restart: always
    networks:
      - gekiyasutokkacom

  nginx:
    image: nginx:1.27.4
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/https.conf:/etc/nginx/conf.d/https.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - ./nginx/private.key:/etc/nginx/private.key:ro
    extra_hosts:
      - "gekiyasutokka.com:116.80.90.154"
    ports:
      - "8081:80"
      - "443:443"
    restart: always
    networks:
      - gekiyasutokkacom
networks:
  gekiyasutokkacom:
